name: tinder_with_chuck
description: One joke at a time that changes by tapping a button or swiping card

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  photo_card_swiper: ^0.0.6
  http: ^0.13.5
  json_annotation: ^4.8.0
  appinio_swiper: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1



flutter:

  uses-material-design: true
