name: tinder_with_chuck
description: One joke at a time that changes by tapping a button or swiping card

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  http: ^0.13.5
  json_annotation: ^4.8.0
  flutter_card_swiper: ^2.1.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  flutter_riverpod: ^2.3.2
  flutterfire_ui: ^0.4.3+20
  freezed_annotation: ^2.2.0
  firebase_database: ^10.0.16
  firebase_crashlytics: ^3.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  dependency_validator: ^3.0.0
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  image_path_android: "assets/images/chuck-norris-100.png"
  image_path_ios: "assets/images/chuck-norris-100.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 19
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/images/chuck-norris-100.png"

flutter:

  uses-material-design: true
